#! /bin/bash

main() {
  # cd server/
  python3.9 -m venv venv
  source venv/bin/activate
  venv/bin/pip3 install --upgrade pip
  venv/bin/pip3 install -r requirements.txt
  deactivate
  # cd ../
}

main
